[mypy]
python_version = 3.10
mypy_path = .
explicit_package_bases = True
ignore_missing_imports = True
show_error_codes = True
warn_redundant_casts = True
warn_unused_configs = True
no_implicit_optional = False
disable_error_code = override, union-attr, attr-defined, metaclass

[mypy-openpyxl.*]
ignore_missing_imports = True

[mypy-defusedxml.*]
ignore_missing_imports = True

[mypy-docx.*]
ignore_missing_imports = True

[mypy-pptx.*]
ignore_missing_imports = True

[mypy-pypdf.*]
ignore_missing_imports = True

[mypy-chardet.*]
ignore_missing_imports = True
